# Generated by Django 3.2.2 on 2021-05-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='write',
            new_name='writer',
        ),
    ]
