# Generated by Django 3.2.2 on 2021-05-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_write_blog_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='writer',
            new_name='write',
        ),
    ]
